apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gunicorn-service
  labels: 
    app: {{ .Values.labels.frontend }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 8050
      protocol: TCP
      name: gunicorn-ext
  selector:
    app: {{ .Values.labels.frontend }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mount-src
data:
{{- (.Files.Glob "src/**").AsConfig | nindent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels: 
    app: {{ .Values.labels.frontend }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.frontend }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.frontend }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: src-files
          mountPath: /tmp/dashboard
        ports:
          - name: mongodb
            containerPort: 27017
            protocol: TCP
          - name: gunicorn
            containerPort: 8050
            protocol: TCP
        command: ["/bin/bash", "-c"]
        args:
        - mkdir /dashboard && cp /tmp/dashboard/* /dashboard && 
          cd dashboard && mkdir assets && mv style.css assets &&
          conda init && source ~/.bashrc && 
          conda env create -f /dashboard/conda.yml && conda activate dashboard_env && 
          gunicorn dashboard:server -b 0.0.0.0:8050 -w 2
        env:
          - name: SECRET_PW
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodb
                key: mongodb-root-password
          - name: SVC_NAME
            value: "{{ .Release.Name }}-mongodb"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: src-files
        configMap:
          name: mount-src
