apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  labels:
    app: {{ .Values.labels.init }}
spec:
  ttlSecondsAfterFinished: 120
  template:
      spec:
        containers:
        - name: init
          image: ubuntu
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
            name: mongodb-conn
          command: ["/bin/sh", "-c"]
          args:
          - "cd tmp && apt-get update && apt-get install curl jq -y &&
            curl -LJO {{ .Values.links.mongotools }} &&
            tar -zxvf ./{{ .Values.links.pkg }}.tgz &&
            mv ./{{ .Values.links.pkg }}/bin/mongoimport /usr/local/bin &&
            curl -s '{{ .Values.links.datagov }}&limit=300' | jq '.result.records[] | {pr_date: .pr_date, age_group: .age_group, count_of_case: .count_of_case}' | jq -s '.' >> sg_covid.json &&
            mongoimport -d covid -c sg --authenticationDatabase admin -u root -p $(SECRET_PW) --drop \
            --file sg_covid.json -h {{ .Release.Name }}-mongodb:27017 --jsonArray"
          env:
          - name: SECRET_PW
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodb
                key: mongodb-root-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        restartPolicy: "OnFailure"