apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  labels:
    app: {{ .Values.labels.backend }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: {{ .Values.labels.backend }}
